name: Build on Merge to Main
run-name: Build after the code merge.

on:
  push:
    branches:
      - main
      - master # Runs only when code is pushed/merged into main branch
#  pull_request_target:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 4: Resolve dependencies
      - name: Resolve maven dependencies
        run: mvn dependency:resolve

      # Step 5: Build a JAR
      - name: Build a .jar of the project
        run: mvn package

     # Step 6 build docker image
      - name: Build docker image
        run: docker build -t springAIChatBot .

      # Step 7: Run the spring project
      - name: Run the spring project
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: mvn spring-boot:run
